version: '3.7'

services:
  sqledge:
    image: mcr.microsoft.com/azure-sql-edge
    cap_add:
      - SYS_PTRACE
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_SA_USERNAME=username
    network_mode: "host"
