version: '3.7'

services:
  app:
    build:
      context: .
    depends_on:
      - db
    network_mode: "host"

  db:
    image: mcr.microsoft.com/azure-sql-edge
    cap_add:
      - SYS_PTRACE
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_SA_USERNAME=username
    network_mode: "host"
